### ISSUE TITLE
[persist_theme] bug in source

### ISSUE THREAD

**Issue by alexmik95** [AppleEducate/plugins#47]
## Steps to Reproduce
simply import in pubspec.yaml and build any project that use this plugin.
Obviously it requires some attributes that are not passed.

## Logs
file:///$HOME/flutter/.pub-cache/hosted/pub.dartlang.org/persist_theme-1.0.4/lib/ui/pickers/picker.dart:34:23: Error: Too few positional arguments: 2 required, 0 given.
    return ColorPicker(
               ^

**Comment by noobiek** [comment]
ColorPicker class constructor awaits 2 positional arguments, see:
https://github.com/mchome/flutter_colorpicker/blob/master/lib/flutter_colorpicker.dart
But picker.dart calls it like this:
```
return ColorPicker(
      pickerColor: value,
      onColorChanged: onChanged,
      enableLabel: true,
      pickerAreaHeightPercent: 0.8,
    );
```
When it should be
```
return ColorPicker(
      value,
      onChanged,
      enableLabel: true,
      pickerAreaHeightPercent: 0.8,
    );
```

**Comment by alexmik95** [comment]
@noobiek thanks :) I noticed it too by trying several times. the repository should be fixed and updated but i'm new on github and don't know how to pull request. i'll try..

**Comment by noobiek** [comment]
@alexmik95, my message was just a clarification for the maintainer to save time finding the issue.

Your PR will anyway require maintainer to pull, so I think it would be faster if just @AppleEducate himselft made the fix. I guess there will be some testing involved as well.
And you shouldn't have closed this issue yet. It's not fixed yet, is it?
